# Generated by Django 4.1.2 on 2022-10-20 07:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_setting_contact_alter_setting_aboutus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
