# Generated by Django 4.1.2 on 2022-10-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_setting_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=20)),
                ('mail', models.CharField(blank=True, max_length=55)),
                ('konu', models.CharField(blank=True, max_length=55)),
                ('mesaj', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read')], default='New', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('note', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
