# Generated by Django 4.1.2 on 2022-10-22 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactformmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormMessage',
        ),
    ]
